# Generated by Django 4.2.20 on 2025-04-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('registrering', models.DateField()),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=255, null=True)),
                ('horsepower', models.IntegerField(blank=True, null=True)),
                ('engine_size', models.IntegerField(blank=True, null=True)),
                ('transimision', models.CharField(blank=True, max_length=255, null=True)),
                ('kilometer', models.IntegerField(blank=True, null=True)),
                ('number_of_doors', models.IntegerField(blank=True, null=True)),
                ('number_of_seats', models.IntegerField(blank=True, null=True)),
                ('karosseri', models.CharField(blank=True, max_length=255, null=True)),
                ('koretype', models.CharField(blank=True, max_length=255, null=True)),
                ('kosmetisk', models.IntegerField(blank=True, null=True)),
                ('mekanisk', models.CharField(blank=True, max_length=255, null=True)),
                ('kommentar', models.CharField(blank=True, max_length=255, null=True)),
                ('registeringsafgift', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_moms_or_inkl', models.CharField(blank=True, max_length=255, null=True)),
                ('stelnummer', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('unique_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('image_names', models.TextField(default='notavailable.jpg', max_length=2000)),
                ('image_url_1', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url_2', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url_3', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url_4', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url_5', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
