# Generated by Django 4.2.20 on 2025-04-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('brand', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('engine_size', models.IntegerField()),
                ('horsepower', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image_names', models.TextField(default='notavailable.jpg', max_length=2000)),
            ],
        ),
    ]
