# Generated by Django 4.2.20 on 2025-04-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.ImageField(upload_to='car_images/'),
        ),
    ]
