# Generated by Django 4.2.20 on 2025-07-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_alter_car_kommentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
