# Generated by Django 4.2.20 on 2025-04-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_alter_image_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.CharField(max_length=255),
        ),
    ]
