# Generated by Django 4.2.20 on 2025-04-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_alter_image_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_names',
            field=models.TextField(default='notavailable.jpg', max_length=2000),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
